// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: api/proto/core.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ServerCommand_CommandType int32

const (
	ServerCommand_NONE         ServerCommand_CommandType = 0
	ServerCommand_SHAKE_MOUSE  ServerCommand_CommandType = 1 // 졸음 깨우기 (물리)
	ServerCommand_BLOCK_SCREEN ServerCommand_CommandType = 2 // 화면 가리기 (딴짓)
	ServerCommand_SHOW_MESSAGE ServerCommand_CommandType = 3 // 경고 메시지/RAG 결과 띄우기
	ServerCommand_PLAY_SOUND   ServerCommand_CommandType = 4 // TTS 읽기
)

// Enum value maps for ServerCommand_CommandType.
var (
	ServerCommand_CommandType_name = map[int32]string{
		0: "NONE",
		1: "SHAKE_MOUSE",
		2: "BLOCK_SCREEN",
		3: "SHOW_MESSAGE",
		4: "PLAY_SOUND",
	}
	ServerCommand_CommandType_value = map[string]int32{
		"NONE":         0,
		"SHAKE_MOUSE":  1,
		"BLOCK_SCREEN": 2,
		"SHOW_MESSAGE": 3,
		"PLAY_SOUND":   4,
	}
)

func (x ServerCommand_CommandType) Enum() *ServerCommand_CommandType {
	p := new(ServerCommand_CommandType)
	*p = x
	return p
}

func (x ServerCommand_CommandType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServerCommand_CommandType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_core_proto_enumTypes[0].Descriptor()
}

func (ServerCommand_CommandType) Type() protoreflect.EnumType {
	return &file_api_proto_core_proto_enumTypes[0]
}

func (x ServerCommand_CommandType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServerCommand_CommandType.Descriptor instead.
func (ServerCommand_CommandType) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_core_proto_rawDescGZIP(), []int{1, 0}
}

// --- 클라이언트 -> 서버 (1초마다 전송) ---
type ClientHeartbeat struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	ClientId string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"` // "pc-01", "cam-01"
	// OS 활동 통계 (Dev 1용)
	MouseDistance  int32 `protobuf:"varint,2,opt,name=mouse_distance,json=mouseDistance,proto3" json:"mouse_distance,omitempty"`    // 1초간 이동 거리 합
	ClickCount     int32 `protobuf:"varint,3,opt,name=click_count,json=clickCount,proto3" json:"click_count,omitempty"`             // 1초간 클릭 수
	KeystrokeCount int32 `protobuf:"varint,4,opt,name=keystroke_count,json=keystrokeCount,proto3" json:"keystroke_count,omitempty"` // 1초간 키 입력 수
	IsOsIdle       bool  `protobuf:"varint,5,opt,name=is_os_idle,json=isOsIdle,proto3" json:"is_os_idle,omitempty"`                 // OS 유휴 상태 여부
	// 비전 데이터 (Dev 2용)
	IsEyesClosed       bool    `protobuf:"varint,6,opt,name=is_eyes_closed,json=isEyesClosed,proto3" json:"is_eyes_closed,omitempty"`                  // 눈 감음 여부
	ConcentrationScore float32 `protobuf:"fixed32,7,opt,name=concentration_score,json=concentrationScore,proto3" json:"concentration_score,omitempty"` // 비전 모델이 판단한 집중도
	KeyboardEntropy    float32 `protobuf:"fixed32,8,opt,name=keyboard_entropy,json=keyboardEntropy,proto3" json:"keyboard_entropy,omitempty"`          // 키보드 엔트로피 (0.0 ~ 5.0)
	ActiveWindowTitle  string  `protobuf:"bytes,9,opt,name=active_window_title,json=activeWindowTitle,proto3" json:"active_window_title,omitempty"`    // 활성 창 제목
	IsDragging         bool    `protobuf:"varint,10,opt,name=is_dragging,json=isDragging,proto3" json:"is_dragging,omitempty"`                         // 마우스 드래그 여부
	AvgDwellTime       float64 `protobuf:"fixed64,11,opt,name=avg_dwell_time,json=avgDwellTime,proto3" json:"avg_dwell_time,omitempty"`                // 평균 키 누름 시간 (ms)
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ClientHeartbeat) Reset() {
	*x = ClientHeartbeat{}
	mi := &file_api_proto_core_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientHeartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientHeartbeat) ProtoMessage() {}

func (x *ClientHeartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_core_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientHeartbeat.ProtoReflect.Descriptor instead.
func (*ClientHeartbeat) Descriptor() ([]byte, []int) {
	return file_api_proto_core_proto_rawDescGZIP(), []int{0}
}

func (x *ClientHeartbeat) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *ClientHeartbeat) GetMouseDistance() int32 {
	if x != nil {
		return x.MouseDistance
	}
	return 0
}

func (x *ClientHeartbeat) GetClickCount() int32 {
	if x != nil {
		return x.ClickCount
	}
	return 0
}

func (x *ClientHeartbeat) GetKeystrokeCount() int32 {
	if x != nil {
		return x.KeystrokeCount
	}
	return 0
}

func (x *ClientHeartbeat) GetIsOsIdle() bool {
	if x != nil {
		return x.IsOsIdle
	}
	return false
}

func (x *ClientHeartbeat) GetIsEyesClosed() bool {
	if x != nil {
		return x.IsEyesClosed
	}
	return false
}

func (x *ClientHeartbeat) GetConcentrationScore() float32 {
	if x != nil {
		return x.ConcentrationScore
	}
	return 0
}

func (x *ClientHeartbeat) GetKeyboardEntropy() float32 {
	if x != nil {
		return x.KeyboardEntropy
	}
	return 0
}

func (x *ClientHeartbeat) GetActiveWindowTitle() string {
	if x != nil {
		return x.ActiveWindowTitle
	}
	return ""
}

func (x *ClientHeartbeat) GetIsDragging() bool {
	if x != nil {
		return x.IsDragging
	}
	return false
}

func (x *ClientHeartbeat) GetAvgDwellTime() float64 {
	if x != nil {
		return x.AvgDwellTime
	}
	return 0
}

// --- 서버 -> 클라이언트 (명령) ---
type ServerCommand struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Type          ServerCommand_CommandType `protobuf:"varint,1,opt,name=type,proto3,enum=jiaa.core.ServerCommand_CommandType" json:"type,omitempty"`
	Payload       string                    `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"` // 메시지 내용이나 추가 정보
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerCommand) Reset() {
	*x = ServerCommand{}
	mi := &file_api_proto_core_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerCommand) ProtoMessage() {}

func (x *ServerCommand) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_core_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerCommand.ProtoReflect.Descriptor instead.
func (*ServerCommand) Descriptor() ([]byte, []int) {
	return file_api_proto_core_proto_rawDescGZIP(), []int{1}
}

func (x *ServerCommand) GetType() ServerCommand_CommandType {
	if x != nil {
		return x.Type
	}
	return ServerCommand_NONE
}

func (x *ServerCommand) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

// --- AI 결과 보고 ---
type AnalysisReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`       // "EMERGENCY", "URL_BLOCK"
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"` // 상세 내용
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalysisReport) Reset() {
	*x = AnalysisReport{}
	mi := &file_api_proto_core_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalysisReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalysisReport) ProtoMessage() {}

func (x *AnalysisReport) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_core_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalysisReport.ProtoReflect.Descriptor instead.
func (*AnalysisReport) Descriptor() ([]byte, []int) {
	return file_api_proto_core_proto_rawDescGZIP(), []int{2}
}

func (x *AnalysisReport) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *AnalysisReport) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_api_proto_core_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_core_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_api_proto_core_proto_rawDescGZIP(), []int{3}
}

func (x *Ack) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type AppListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppsJson      string                 `protobuf:"bytes,1,opt,name=apps_json,json=appsJson,proto3" json:"apps_json,omitempty"` // 실행 중인 앱 목록 JSON (["Chrome", "VS Code", ...])
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`              // 전송 시간
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppListRequest) Reset() {
	*x = AppListRequest{}
	mi := &file_api_proto_core_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppListRequest) ProtoMessage() {}

func (x *AppListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_core_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppListRequest.ProtoReflect.Descriptor instead.
func (*AppListRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_core_proto_rawDescGZIP(), []int{4}
}

func (x *AppListRequest) GetAppsJson() string {
	if x != nil {
		return x.AppsJson
	}
	return ""
}

func (x *AppListRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type AppListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`                     // 수신 성공 여부
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                      // 응답 메시지
	Command       string                 `protobuf:"bytes,3,opt,name=command,proto3" json:"command,omitempty"`                      // 명령 (e.g. "KILL")
	TargetApp     string                 `protobuf:"bytes,4,opt,name=target_app,json=targetApp,proto3" json:"target_app,omitempty"` // 대상 앱 (e.g. "Minecraft")
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppListResponse) Reset() {
	*x = AppListResponse{}
	mi := &file_api_proto_core_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppListResponse) ProtoMessage() {}

func (x *AppListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_core_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppListResponse.ProtoReflect.Descriptor instead.
func (*AppListResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_core_proto_rawDescGZIP(), []int{5}
}

func (x *AppListResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AppListResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AppListResponse) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *AppListResponse) GetTargetApp() string {
	if x != nil {
		return x.TargetApp
	}
	return ""
}

type AudioRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AudioData     []byte                 `protobuf:"bytes,1,opt,name=audio_data,json=audioData,proto3" json:"audio_data,omitempty"`               // VAD로 걸러진 음성 바이너리
	IsFinal       bool                   `protobuf:"varint,2,opt,name=is_final,json=isFinal,proto3" json:"is_final,omitempty"`                    // True = "문장 끝났음(침묵 1초 감지)"
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                               // 로깅용 시간
	MediaInfoJson string                 `protobuf:"bytes,4,opt,name=media_info_json,json=mediaInfoJson,proto3" json:"media_info_json,omitempty"` // 미디어 정보 JSON
	ProcessInfo   string                 `protobuf:"bytes,10,opt,name=process_info,json=processInfo,proto3" json:"process_info,omitempty"`        // (추가) 현재 활성 프로세스 정보 (JSON)
	Windows       string                 `protobuf:"bytes,11,opt,name=windows,proto3" json:"windows,omitempty"`                                   // (추가) 열린 창 목록 정보 (JSON)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudioRequest) Reset() {
	*x = AudioRequest{}
	mi := &file_api_proto_core_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioRequest) ProtoMessage() {}

func (x *AudioRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_core_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioRequest.ProtoReflect.Descriptor instead.
func (*AudioRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_core_proto_rawDescGZIP(), []int{6}
}

func (x *AudioRequest) GetAudioData() []byte {
	if x != nil {
		return x.AudioData
	}
	return nil
}

func (x *AudioRequest) GetIsFinal() bool {
	if x != nil {
		return x.IsFinal
	}
	return false
}

func (x *AudioRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *AudioRequest) GetMediaInfoJson() string {
	if x != nil {
		return x.MediaInfoJson
	}
	return ""
}

func (x *AudioRequest) GetProcessInfo() string {
	if x != nil {
		return x.ProcessInfo
	}
	return ""
}

func (x *AudioRequest) GetWindows() string {
	if x != nil {
		return x.Windows
	}
	return ""
}

type AudioResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transcript    string                 `protobuf:"bytes,1,opt,name=transcript,proto3" json:"transcript,omitempty"`                       // 변환된 텍스트
	IsEmergency   bool                   `protobuf:"varint,2,opt,name=is_emergency,json=isEmergency,proto3" json:"is_emergency,omitempty"` // 위급 상황 여부
	Intent        string                 `protobuf:"bytes,3,opt,name=intent,proto3" json:"intent,omitempty"`                               // 의도 분석 결과
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudioResponse) Reset() {
	*x = AudioResponse{}
	mi := &file_api_proto_core_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioResponse) ProtoMessage() {}

func (x *AudioResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_core_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioResponse.ProtoReflect.Descriptor instead.
func (*AudioResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_core_proto_rawDescGZIP(), []int{7}
}

func (x *AudioResponse) GetTranscript() string {
	if x != nil {
		return x.Transcript
	}
	return ""
}

func (x *AudioResponse) GetIsEmergency() bool {
	if x != nil {
		return x.IsEmergency
	}
	return false
}

func (x *AudioResponse) GetIntent() string {
	if x != nil {
		return x.Intent
	}
	return ""
}

var File_api_proto_core_proto protoreflect.FileDescriptor

const file_api_proto_core_proto_rawDesc = "" +
	"\n" +
	"\x14api/proto/core.proto\x12\tjiaa.core\"\xb6\x03\n" +
	"\x0fClientHeartbeat\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12%\n" +
	"\x0emouse_distance\x18\x02 \x01(\x05R\rmouseDistance\x12\x1f\n" +
	"\vclick_count\x18\x03 \x01(\x05R\n" +
	"clickCount\x12'\n" +
	"\x0fkeystroke_count\x18\x04 \x01(\x05R\x0ekeystrokeCount\x12\x1c\n" +
	"\n" +
	"is_os_idle\x18\x05 \x01(\bR\bisOsIdle\x12$\n" +
	"\x0eis_eyes_closed\x18\x06 \x01(\bR\fisEyesClosed\x12/\n" +
	"\x13concentration_score\x18\a \x01(\x02R\x12concentrationScore\x12)\n" +
	"\x10keyboard_entropy\x18\b \x01(\x02R\x0fkeyboardEntropy\x12.\n" +
	"\x13active_window_title\x18\t \x01(\tR\x11activeWindowTitle\x12\x1f\n" +
	"\vis_dragging\x18\n" +
	" \x01(\bR\n" +
	"isDragging\x12$\n" +
	"\x0eavg_dwell_time\x18\v \x01(\x01R\favgDwellTime\"\xc1\x01\n" +
	"\rServerCommand\x128\n" +
	"\x04type\x18\x01 \x01(\x0e2$.jiaa.core.ServerCommand.CommandTypeR\x04type\x12\x18\n" +
	"\apayload\x18\x02 \x01(\tR\apayload\"\\\n" +
	"\vCommandType\x12\b\n" +
	"\x04NONE\x10\x00\x12\x0f\n" +
	"\vSHAKE_MOUSE\x10\x01\x12\x10\n" +
	"\fBLOCK_SCREEN\x10\x02\x12\x10\n" +
	"\fSHOW_MESSAGE\x10\x03\x12\x0e\n" +
	"\n" +
	"PLAY_SOUND\x10\x04\">\n" +
	"\x0eAnalysisReport\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"\x1f\n" +
	"\x03Ack\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"K\n" +
	"\x0eAppListRequest\x12\x1b\n" +
	"\tapps_json\x18\x01 \x01(\tR\bappsJson\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\"~\n" +
	"\x0fAppListResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x18\n" +
	"\acommand\x18\x03 \x01(\tR\acommand\x12\x1d\n" +
	"\n" +
	"target_app\x18\x04 \x01(\tR\ttargetApp\"\xcb\x01\n" +
	"\fAudioRequest\x12\x1d\n" +
	"\n" +
	"audio_data\x18\x01 \x01(\fR\taudioData\x12\x19\n" +
	"\bis_final\x18\x02 \x01(\bR\aisFinal\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12&\n" +
	"\x0fmedia_info_json\x18\x04 \x01(\tR\rmediaInfoJson\x12!\n" +
	"\fprocess_info\x18\n" +
	" \x01(\tR\vprocessInfo\x12\x18\n" +
	"\awindows\x18\v \x01(\tR\awindows\"j\n" +
	"\rAudioResponse\x12\x1e\n" +
	"\n" +
	"transcript\x18\x01 \x01(\tR\n" +
	"transcript\x12!\n" +
	"\fis_emergency\x18\x02 \x01(\bR\visEmergency\x12\x16\n" +
	"\x06intent\x18\x03 \x01(\tR\x06intent2\xa6\x02\n" +
	"\vCoreService\x12F\n" +
	"\n" +
	"SyncClient\x12\x1a.jiaa.core.ClientHeartbeat\x1a\x18.jiaa.core.ServerCommand(\x010\x01\x12A\n" +
	"\x14ReportAnalysisResult\x12\x19.jiaa.core.AnalysisReport\x1a\x0e.jiaa.core.Ack\x12D\n" +
	"\vSendAppList\x12\x19.jiaa.core.AppListRequest\x1a\x1a.jiaa.core.AppListResponse\x12F\n" +
	"\x0fTranscribeAudio\x12\x17.jiaa.core.AudioRequest\x1a\x18.jiaa.core.AudioResponse(\x01B4\n" +
	"\x14com.jiaa.common.coreP\x01Z\x1ajiaa-server-core/pkg/protob\x06proto3"

var (
	file_api_proto_core_proto_rawDescOnce sync.Once
	file_api_proto_core_proto_rawDescData []byte
)

func file_api_proto_core_proto_rawDescGZIP() []byte {
	file_api_proto_core_proto_rawDescOnce.Do(func() {
		file_api_proto_core_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_core_proto_rawDesc), len(file_api_proto_core_proto_rawDesc)))
	})
	return file_api_proto_core_proto_rawDescData
}

var file_api_proto_core_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_proto_core_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_api_proto_core_proto_goTypes = []any{
	(ServerCommand_CommandType)(0), // 0: jiaa.core.ServerCommand.CommandType
	(*ClientHeartbeat)(nil),        // 1: jiaa.core.ClientHeartbeat
	(*ServerCommand)(nil),          // 2: jiaa.core.ServerCommand
	(*AnalysisReport)(nil),         // 3: jiaa.core.AnalysisReport
	(*Ack)(nil),                    // 4: jiaa.core.Ack
	(*AppListRequest)(nil),         // 5: jiaa.core.AppListRequest
	(*AppListResponse)(nil),        // 6: jiaa.core.AppListResponse
	(*AudioRequest)(nil),           // 7: jiaa.core.AudioRequest
	(*AudioResponse)(nil),          // 8: jiaa.core.AudioResponse
}
var file_api_proto_core_proto_depIdxs = []int32{
	0, // 0: jiaa.core.ServerCommand.type:type_name -> jiaa.core.ServerCommand.CommandType
	1, // 1: jiaa.core.CoreService.SyncClient:input_type -> jiaa.core.ClientHeartbeat
	3, // 2: jiaa.core.CoreService.ReportAnalysisResult:input_type -> jiaa.core.AnalysisReport
	5, // 3: jiaa.core.CoreService.SendAppList:input_type -> jiaa.core.AppListRequest
	7, // 4: jiaa.core.CoreService.TranscribeAudio:input_type -> jiaa.core.AudioRequest
	2, // 5: jiaa.core.CoreService.SyncClient:output_type -> jiaa.core.ServerCommand
	4, // 6: jiaa.core.CoreService.ReportAnalysisResult:output_type -> jiaa.core.Ack
	6, // 7: jiaa.core.CoreService.SendAppList:output_type -> jiaa.core.AppListResponse
	8, // 8: jiaa.core.CoreService.TranscribeAudio:output_type -> jiaa.core.AudioResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_proto_core_proto_init() }
func file_api_proto_core_proto_init() {
	if File_api_proto_core_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_core_proto_rawDesc), len(file_api_proto_core_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_core_proto_goTypes,
		DependencyIndexes: file_api_proto_core_proto_depIdxs,
		EnumInfos:         file_api_proto_core_proto_enumTypes,
		MessageInfos:      file_api_proto_core_proto_msgTypes,
	}.Build()
	File_api_proto_core_proto = out.File
	file_api_proto_core_proto_goTypes = nil
	file_api_proto_core_proto_depIdxs = nil
}
