// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: api/proto/core.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ServerCommand_CommandType int32

const (
	ServerCommand_NONE         ServerCommand_CommandType = 0
	ServerCommand_SHAKE_MOUSE  ServerCommand_CommandType = 1 // 졸음 깨우기 (물리)
	ServerCommand_BLOCK_SCREEN ServerCommand_CommandType = 2 // 화면 가리기 (딴짓)
	ServerCommand_SHOW_MESSAGE ServerCommand_CommandType = 3 // 경고 메시지/RAG 결과 띄우기
	ServerCommand_PLAY_SOUND   ServerCommand_CommandType = 4 // TTS 읽기
)

// Enum value maps for ServerCommand_CommandType.
var (
	ServerCommand_CommandType_name = map[int32]string{
		0: "NONE",
		1: "SHAKE_MOUSE",
		2: "BLOCK_SCREEN",
		3: "SHOW_MESSAGE",
		4: "PLAY_SOUND",
	}
	ServerCommand_CommandType_value = map[string]int32{
		"NONE":         0,
		"SHAKE_MOUSE":  1,
		"BLOCK_SCREEN": 2,
		"SHOW_MESSAGE": 3,
		"PLAY_SOUND":   4,
	}
)

func (x ServerCommand_CommandType) Enum() *ServerCommand_CommandType {
	p := new(ServerCommand_CommandType)
	*p = x
	return p
}

func (x ServerCommand_CommandType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServerCommand_CommandType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_core_proto_enumTypes[0].Descriptor()
}

func (ServerCommand_CommandType) Type() protoreflect.EnumType {
	return &file_api_proto_core_proto_enumTypes[0]
}

func (x ServerCommand_CommandType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServerCommand_CommandType.Descriptor instead.
func (ServerCommand_CommandType) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_core_proto_rawDescGZIP(), []int{1, 0}
}

// --- 클라이언트 -> 서버 (1초마다 전송) ---
type ClientHeartbeat struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	ClientId string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"` // "pc-01", "cam-01"
	// OS 활동 통계 (Dev 1용)
	MouseDistance  int32 `protobuf:"varint,2,opt,name=mouse_distance,json=mouseDistance,proto3" json:"mouse_distance,omitempty"`    // 1초간 이동 거리 합
	ClickCount     int32 `protobuf:"varint,3,opt,name=click_count,json=clickCount,proto3" json:"click_count,omitempty"`             // 1초간 클릭 수
	KeystrokeCount int32 `protobuf:"varint,4,opt,name=keystroke_count,json=keystrokeCount,proto3" json:"keystroke_count,omitempty"` // 1초간 키 입력 수
	IsOsIdle       bool  `protobuf:"varint,5,opt,name=is_os_idle,json=isOsIdle,proto3" json:"is_os_idle,omitempty"`                 // OS 유휴 상태 여부
	// 비전 데이터 (Dev 2용)
	IsEyesClosed       bool    `protobuf:"varint,6,opt,name=is_eyes_closed,json=isEyesClosed,proto3" json:"is_eyes_closed,omitempty"`                  // 눈 감음 여부
	ConcentrationScore float32 `protobuf:"fixed32,7,opt,name=concentration_score,json=concentrationScore,proto3" json:"concentration_score,omitempty"` // 비전 모델이 판단한 집중도
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ClientHeartbeat) Reset() {
	*x = ClientHeartbeat{}
	mi := &file_api_proto_core_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientHeartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientHeartbeat) ProtoMessage() {}

func (x *ClientHeartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_core_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientHeartbeat.ProtoReflect.Descriptor instead.
func (*ClientHeartbeat) Descriptor() ([]byte, []int) {
	return file_api_proto_core_proto_rawDescGZIP(), []int{0}
}

func (x *ClientHeartbeat) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *ClientHeartbeat) GetMouseDistance() int32 {
	if x != nil {
		return x.MouseDistance
	}
	return 0
}

func (x *ClientHeartbeat) GetClickCount() int32 {
	if x != nil {
		return x.ClickCount
	}
	return 0
}

func (x *ClientHeartbeat) GetKeystrokeCount() int32 {
	if x != nil {
		return x.KeystrokeCount
	}
	return 0
}

func (x *ClientHeartbeat) GetIsOsIdle() bool {
	if x != nil {
		return x.IsOsIdle
	}
	return false
}

func (x *ClientHeartbeat) GetIsEyesClosed() bool {
	if x != nil {
		return x.IsEyesClosed
	}
	return false
}

func (x *ClientHeartbeat) GetConcentrationScore() float32 {
	if x != nil {
		return x.ConcentrationScore
	}
	return 0
}

// --- 서버 -> 클라이언트 (명령) ---
type ServerCommand struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Type          ServerCommand_CommandType `protobuf:"varint,1,opt,name=type,proto3,enum=jiaa.core.ServerCommand_CommandType" json:"type,omitempty"`
	Payload       string                    `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"` // 메시지 내용이나 추가 정보
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerCommand) Reset() {
	*x = ServerCommand{}
	mi := &file_api_proto_core_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerCommand) ProtoMessage() {}

func (x *ServerCommand) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_core_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerCommand.ProtoReflect.Descriptor instead.
func (*ServerCommand) Descriptor() ([]byte, []int) {
	return file_api_proto_core_proto_rawDescGZIP(), []int{1}
}

func (x *ServerCommand) GetType() ServerCommand_CommandType {
	if x != nil {
		return x.Type
	}
	return ServerCommand_NONE
}

func (x *ServerCommand) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

// --- AI 결과 보고 ---
type AnalysisReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`       // "EMERGENCY", "URL_BLOCK"
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"` // 상세 내용
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalysisReport) Reset() {
	*x = AnalysisReport{}
	mi := &file_api_proto_core_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalysisReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalysisReport) ProtoMessage() {}

func (x *AnalysisReport) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_core_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalysisReport.ProtoReflect.Descriptor instead.
func (*AnalysisReport) Descriptor() ([]byte, []int) {
	return file_api_proto_core_proto_rawDescGZIP(), []int{2}
}

func (x *AnalysisReport) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *AnalysisReport) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_api_proto_core_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_core_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_api_proto_core_proto_rawDescGZIP(), []int{3}
}

func (x *Ack) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_api_proto_core_proto protoreflect.FileDescriptor

const file_api_proto_core_proto_rawDesc = "" +
	"\n" +
	"\x14api/proto/core.proto\x12\tjiaa.core\"\x94\x02\n" +
	"\x0fClientHeartbeat\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12%\n" +
	"\x0emouse_distance\x18\x02 \x01(\x05R\rmouseDistance\x12\x1f\n" +
	"\vclick_count\x18\x03 \x01(\x05R\n" +
	"clickCount\x12'\n" +
	"\x0fkeystroke_count\x18\x04 \x01(\x05R\x0ekeystrokeCount\x12\x1c\n" +
	"\n" +
	"is_os_idle\x18\x05 \x01(\bR\bisOsIdle\x12$\n" +
	"\x0eis_eyes_closed\x18\x06 \x01(\bR\fisEyesClosed\x12/\n" +
	"\x13concentration_score\x18\a \x01(\x02R\x12concentrationScore\"\xc1\x01\n" +
	"\rServerCommand\x128\n" +
	"\x04type\x18\x01 \x01(\x0e2$.jiaa.core.ServerCommand.CommandTypeR\x04type\x12\x18\n" +
	"\apayload\x18\x02 \x01(\tR\apayload\"\\\n" +
	"\vCommandType\x12\b\n" +
	"\x04NONE\x10\x00\x12\x0f\n" +
	"\vSHAKE_MOUSE\x10\x01\x12\x10\n" +
	"\fBLOCK_SCREEN\x10\x02\x12\x10\n" +
	"\fSHOW_MESSAGE\x10\x03\x12\x0e\n" +
	"\n" +
	"PLAY_SOUND\x10\x04\">\n" +
	"\x0eAnalysisReport\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"\x1f\n" +
	"\x03Ack\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\x98\x01\n" +
	"\vCoreService\x12F\n" +
	"\n" +
	"SyncClient\x12\x1a.jiaa.core.ClientHeartbeat\x1a\x18.jiaa.core.ServerCommand(\x010\x01\x12A\n" +
	"\x14ReportAnalysisResult\x12\x19.jiaa.core.AnalysisReport\x1a\x0e.jiaa.core.AckB4\n" +
	"\x14com.jiaa.common.coreP\x01Z\x1ajiaa-server-core/pkg/protob\x06proto3"

var (
	file_api_proto_core_proto_rawDescOnce sync.Once
	file_api_proto_core_proto_rawDescData []byte
)

func file_api_proto_core_proto_rawDescGZIP() []byte {
	file_api_proto_core_proto_rawDescOnce.Do(func() {
		file_api_proto_core_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_core_proto_rawDesc), len(file_api_proto_core_proto_rawDesc)))
	})
	return file_api_proto_core_proto_rawDescData
}

var file_api_proto_core_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_proto_core_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_proto_core_proto_goTypes = []any{
	(ServerCommand_CommandType)(0), // 0: jiaa.core.ServerCommand.CommandType
	(*ClientHeartbeat)(nil),        // 1: jiaa.core.ClientHeartbeat
	(*ServerCommand)(nil),          // 2: jiaa.core.ServerCommand
	(*AnalysisReport)(nil),         // 3: jiaa.core.AnalysisReport
	(*Ack)(nil),                    // 4: jiaa.core.Ack
}
var file_api_proto_core_proto_depIdxs = []int32{
	0, // 0: jiaa.core.ServerCommand.type:type_name -> jiaa.core.ServerCommand.CommandType
	1, // 1: jiaa.core.CoreService.SyncClient:input_type -> jiaa.core.ClientHeartbeat
	3, // 2: jiaa.core.CoreService.ReportAnalysisResult:input_type -> jiaa.core.AnalysisReport
	2, // 3: jiaa.core.CoreService.SyncClient:output_type -> jiaa.core.ServerCommand
	4, // 4: jiaa.core.CoreService.ReportAnalysisResult:output_type -> jiaa.core.Ack
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_proto_core_proto_init() }
func file_api_proto_core_proto_init() {
	if File_api_proto_core_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_core_proto_rawDesc), len(file_api_proto_core_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_core_proto_goTypes,
		DependencyIndexes: file_api_proto_core_proto_depIdxs,
		EnumInfos:         file_api_proto_core_proto_enumTypes,
		MessageInfos:      file_api_proto_core_proto_msgTypes,
	}.Build()
	File_api_proto_core_proto = out.File
	file_api_proto_core_proto_goTypes = nil
	file_api_proto_core_proto_depIdxs = nil
}
