// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.31.1
// source: core.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CoreService_SyncClient_FullMethodName           = "/jiaa.core.CoreService/SyncClient"
	CoreService_ReportAnalysisResult_FullMethodName = "/jiaa.core.CoreService/ReportAnalysisResult"
)

// CoreServiceClient is the client API for CoreService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CoreServiceClient interface {
	// 1. 클라이언트(OS/Vision) 연결: 센서 정보 주고 <-> 명령 받고 (양방향)
	SyncClient(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ClientHeartbeat, ServerCommand], error)
	// 2. AI 분석 결과 보고 (윤성 -> 승민)
	ReportAnalysisResult(ctx context.Context, in *AnalysisReport, opts ...grpc.CallOption) (*Ack, error)
}

type coreServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCoreServiceClient(cc grpc.ClientConnInterface) CoreServiceClient {
	return &coreServiceClient{cc}
}

func (c *coreServiceClient) SyncClient(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ClientHeartbeat, ServerCommand], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CoreService_ServiceDesc.Streams[0], CoreService_SyncClient_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ClientHeartbeat, ServerCommand]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CoreService_SyncClientClient = grpc.BidiStreamingClient[ClientHeartbeat, ServerCommand]

func (c *coreServiceClient) ReportAnalysisResult(ctx context.Context, in *AnalysisReport, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, CoreService_ReportAnalysisResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CoreServiceServer is the server API for CoreService service.
// All implementations must embed UnimplementedCoreServiceServer
// for forward compatibility.
type CoreServiceServer interface {
	// 1. 클라이언트(OS/Vision) 연결: 센서 정보 주고 <-> 명령 받고 (양방향)
	SyncClient(grpc.BidiStreamingServer[ClientHeartbeat, ServerCommand]) error
	// 2. AI 분석 결과 보고 (윤성 -> 승민)
	ReportAnalysisResult(context.Context, *AnalysisReport) (*Ack, error)
	mustEmbedUnimplementedCoreServiceServer()
}

// UnimplementedCoreServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCoreServiceServer struct{}

func (UnimplementedCoreServiceServer) SyncClient(grpc.BidiStreamingServer[ClientHeartbeat, ServerCommand]) error {
	return status.Error(codes.Unimplemented, "method SyncClient not implemented")
}
func (UnimplementedCoreServiceServer) ReportAnalysisResult(context.Context, *AnalysisReport) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportAnalysisResult not implemented")
}
func (UnimplementedCoreServiceServer) mustEmbedUnimplementedCoreServiceServer() {}
func (UnimplementedCoreServiceServer) testEmbeddedByValue()                     {}

// UnsafeCoreServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CoreServiceServer will
// result in compilation errors.
type UnsafeCoreServiceServer interface {
	mustEmbedUnimplementedCoreServiceServer()
}

func RegisterCoreServiceServer(s grpc.ServiceRegistrar, srv CoreServiceServer) {
	// If the following call panics, it indicates UnimplementedCoreServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CoreService_ServiceDesc, srv)
}

func _CoreService_SyncClient_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CoreServiceServer).SyncClient(&grpc.GenericServerStream[ClientHeartbeat, ServerCommand]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CoreService_SyncClientServer = grpc.BidiStreamingServer[ClientHeartbeat, ServerCommand]

func _CoreService_ReportAnalysisResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnalysisReport)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).ReportAnalysisResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_ReportAnalysisResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).ReportAnalysisResult(ctx, req.(*AnalysisReport))
	}
	return interceptor(ctx, in, info, handler)
}

// CoreService_ServiceDesc is the grpc.ServiceDesc for CoreService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CoreService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "jiaa.core.CoreService",
	HandlerType: (*CoreServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReportAnalysisResult",
			Handler:    _CoreService_ReportAnalysisResult_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SyncClient",
			Handler:       _CoreService_SyncClient_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "core.proto",
}
