// Code generated by protoc-gen-go. DO NOT EDIT.
// source: physical_control.proto

package proto

import (
	"context"

	"google.golang.org/grpc"
)

// PhysicalActionType 물리 제어 액션 타입
type PhysicalActionType int32

const (
	PhysicalActionType_PHYSICAL_ACTION_UNKNOWN PhysicalActionType = 0
	PhysicalActionType_MOUSE_SENSITIVITY_DOWN  PhysicalActionType = 1
	PhysicalActionType_WINDOW_SHAKE            PhysicalActionType = 2
	PhysicalActionType_KEYBOARD_DELAY          PhysicalActionType = 3
	PhysicalActionType_MINIMIZE_ALL            PhysicalActionType = 4
	PhysicalActionType_CLOSE_APP               PhysicalActionType = 5
	PhysicalActionType_MOUSE_LOCK              PhysicalActionType = 6
)

// PhysicalCommandRequest 물리 제어 요청
type PhysicalCommandRequest struct {
	ClientId   string             `json:"client_id"`
	ActionType PhysicalActionType `json:"action_type"`
	Intensity  int32              `json:"intensity"`
	Message    string             `json:"message"`
	Params     map[string]string  `json:"params"`
}

// PhysicalCommandResponse 물리 제어 응답
type PhysicalCommandResponse struct {
	Success   bool   `json:"success"`
	ErrorCode string `json:"error_code"`
	Message   string `json:"message"`
}

// SetZeroRequest 영점 조절 요청
type SetZeroRequest struct {
	ClientId string `json:"client_id"`
}

// SetZeroResponse 영점 조절 응답
type SetZeroResponse struct {
	Success bool `json:"success"`
}

// PhysicalControlServiceClient gRPC 클라이언트 인터페이스
type PhysicalControlServiceClient interface {
	ExecuteCommand(ctx context.Context, in *PhysicalCommandRequest, opts ...grpc.CallOption) (*PhysicalCommandResponse, error)
	SetZero(ctx context.Context, in *SetZeroRequest, opts ...grpc.CallOption) (*SetZeroResponse, error)
}

type physicalControlServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPhysicalControlServiceClient(cc grpc.ClientConnInterface) PhysicalControlServiceClient {
	return &physicalControlServiceClient{cc}
}

func (c *physicalControlServiceClient) ExecuteCommand(ctx context.Context, in *PhysicalCommandRequest, opts ...grpc.CallOption) (*PhysicalCommandResponse, error) {
	out := new(PhysicalCommandResponse)
	err := c.cc.Invoke(ctx, "/jiaa.PhysicalControlService/ExecuteCommand", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *physicalControlServiceClient) SetZero(ctx context.Context, in *SetZeroRequest, opts ...grpc.CallOption) (*SetZeroResponse, error) {
	out := new(SetZeroResponse)
	err := c.cc.Invoke(ctx, "/jiaa.PhysicalControlService/SetZero", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}
