// Code generated by protoc-gen-go. DO NOT EDIT.
// source: screen_control.proto

package proto

import (
	"context"

	"google.golang.org/grpc"
)

// VisualEffectType 시각 효과 타입
type VisualEffectType int32

const (
	VisualEffectType_VISUAL_EFFECT_UNKNOWN VisualEffectType = 0
	VisualEffectType_SCREEN_GLITCH         VisualEffectType = 1
	VisualEffectType_RED_FLASH             VisualEffectType = 2
	VisualEffectType_SCREEN_SHAKE          VisualEffectType = 3
	VisualEffectType_BLUR_OVERLAY          VisualEffectType = 4
	VisualEffectType_BLACK_SCREEN          VisualEffectType = 5
	VisualEffectType_VIGNETTE              VisualEffectType = 6
)

// AIResultType AI 결과 타입
type AIResultType int32

const (
	AIResultType_AI_RESULT_UNKNOWN AIResultType = 0
	AIResultType_ERROR_SOLUTION    AIResultType = 1
	AIResultType_TIL_CONTENT       AIResultType = 2
	AIResultType_FACT_BOMB         AIResultType = 3
	AIResultType_STUDY_TIP         AIResultType = 4
)

// OverlayType 오버레이 타입
type OverlayType int32

const (
	OverlayType_OVERLAY_UNKNOWN OverlayType = 0
	OverlayType_WARNING         OverlayType = 1
	OverlayType_ERROR           OverlayType = 2
	OverlayType_INFO            OverlayType = 3
	OverlayType_SUCCESS         OverlayType = 4
)

// VisualCommandRequest 시각 명령 요청
type VisualCommandRequest struct {
	ClientId   string           `json:"client_id"`
	EffectType VisualEffectType `json:"effect_type"`
	Intensity  int32            `json:"intensity"`
	DurationMs int32            `json:"duration_ms"`
	Message    string           `json:"message"`
}

// VisualCommandResponse 시각 명령 응답
type VisualCommandResponse struct {
	Success   bool   `json:"success"`
	ErrorCode string `json:"error_code"`
}

// AIResultRequest AI 결과 요청
type AIResultRequest struct {
	ClientId   string       `json:"client_id"`
	Markdown   string       `json:"markdown"`
	Title      string       `json:"title"`
	ResultType AIResultType `json:"result_type"`
}

// AIResultResponse AI 결과 응답
type AIResultResponse struct {
	Success   bool   `json:"success"`
	ErrorCode string `json:"error_code"`
}

// TTSRequest TTS 요청
type TTSRequest struct {
	ClientId string  `json:"client_id"`
	Text     string  `json:"text"`
	Voice    string  `json:"voice"`
	Speed    float32 `json:"speed"`
}

// TTSResponse TTS 응답
type TTSResponse struct {
	Success   bool   `json:"success"`
	ErrorCode string `json:"error_code"`
}

// ScoreUpdateRequest 점수 업데이트 요청
type ScoreUpdateRequest struct {
	ClientId     string `json:"client_id"`
	CurrentScore int32  `json:"current_score"`
	State        string `json:"state"`
}

// ScoreUpdateResponse 점수 업데이트 응답
type ScoreUpdateResponse struct {
	Success bool `json:"success"`
}

// OverlayRequest 오버레이 요청
type OverlayRequest struct {
	ClientId    string      `json:"client_id"`
	Title       string      `json:"title"`
	Message     string      `json:"message"`
	OverlayType OverlayType `json:"overlay_type"`
	DurationMs  int32       `json:"duration_ms"`
}

// OverlayResponse 오버레이 응답
type OverlayResponse struct {
	Success   bool   `json:"success"`
	ErrorCode string `json:"error_code"`
}

// ScreenControlServiceClient gRPC 클라이언트 인터페이스
type ScreenControlServiceClient interface {
	ExecuteVisualCommand(ctx context.Context, in *VisualCommandRequest, opts ...grpc.CallOption) (*VisualCommandResponse, error)
	DisplayAIResult(ctx context.Context, in *AIResultRequest, opts ...grpc.CallOption) (*AIResultResponse, error)
	PlayTTS(ctx context.Context, in *TTSRequest, opts ...grpc.CallOption) (*TTSResponse, error)
	UpdateScoreGauge(ctx context.Context, in *ScoreUpdateRequest, opts ...grpc.CallOption) (*ScoreUpdateResponse, error)
	ShowOverlay(ctx context.Context, in *OverlayRequest, opts ...grpc.CallOption) (*OverlayResponse, error)
}

type screenControlServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewScreenControlServiceClient(cc grpc.ClientConnInterface) ScreenControlServiceClient {
	return &screenControlServiceClient{cc}
}

func (c *screenControlServiceClient) ExecuteVisualCommand(ctx context.Context, in *VisualCommandRequest, opts ...grpc.CallOption) (*VisualCommandResponse, error) {
	out := new(VisualCommandResponse)
	err := c.cc.Invoke(ctx, "/jiaa.ScreenControlService/ExecuteVisualCommand", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *screenControlServiceClient) DisplayAIResult(ctx context.Context, in *AIResultRequest, opts ...grpc.CallOption) (*AIResultResponse, error) {
	out := new(AIResultResponse)
	err := c.cc.Invoke(ctx, "/jiaa.ScreenControlService/DisplayAIResult", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *screenControlServiceClient) PlayTTS(ctx context.Context, in *TTSRequest, opts ...grpc.CallOption) (*TTSResponse, error) {
	out := new(TTSResponse)
	err := c.cc.Invoke(ctx, "/jiaa.ScreenControlService/PlayTTS", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *screenControlServiceClient) UpdateScoreGauge(ctx context.Context, in *ScoreUpdateRequest, opts ...grpc.CallOption) (*ScoreUpdateResponse, error) {
	out := new(ScoreUpdateResponse)
	err := c.cc.Invoke(ctx, "/jiaa.ScreenControlService/UpdateScoreGauge", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *screenControlServiceClient) ShowOverlay(ctx context.Context, in *OverlayRequest, opts ...grpc.CallOption) (*OverlayResponse, error) {
	out := new(OverlayResponse)
	err := c.cc.Invoke(ctx, "/jiaa.ScreenControlService/ShowOverlay", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}
