// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

package proto

import (
	"context"

	"google.golang.org/grpc"
)

// SabotageRequest 사보타주 요청
type SabotageRequest struct {
	ClientId   string `json:"client_id"`
	ActionType string `json:"action_type"`
	Intensity  int32  `json:"intensity"`
	Message    string `json:"message"`
}

// SabotageResponse 사보타주 응답
type SabotageResponse struct {
	Success   bool   `json:"success"`
	ErrorCode string `json:"error_code"`
}

// SabotageCommandServiceClient gRPC 클라이언트 인터페이스
type SabotageCommandServiceClient interface {
	ExecuteSabotage(ctx context.Context, in *SabotageRequest, opts ...grpc.CallOption) (*SabotageResponse, error)
}

type sabotageCommandServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSabotageCommandServiceClient(cc grpc.ClientConnInterface) SabotageCommandServiceClient {
	return &sabotageCommandServiceClient{cc}
}

func (c *sabotageCommandServiceClient) ExecuteSabotage(ctx context.Context, in *SabotageRequest, opts ...grpc.CallOption) (*SabotageResponse, error) {
	out := new(SabotageResponse)
	err := c.cc.Invoke(ctx, "/jiaa.SabotageCommandService/ExecuteSabotage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SabotageCommandServiceServer gRPC 서버 인터페이스
type SabotageCommandServiceServer interface {
	ExecuteSabotage(context.Context, *SabotageRequest) (*SabotageResponse, error)
	mustEmbedUnimplementedSabotageCommandServiceServer()
}

// UnimplementedSabotageCommandServiceServer 기본 구현
type UnimplementedSabotageCommandServiceServer struct{}

func (UnimplementedSabotageCommandServiceServer) ExecuteSabotage(context.Context, *SabotageRequest) (*SabotageResponse, error) {
	return nil, nil
}

func (UnimplementedSabotageCommandServiceServer) mustEmbedUnimplementedSabotageCommandServiceServer() {
}

// RegisterSabotageCommandServiceServer gRPC 서버 등록
func RegisterSabotageCommandServiceServer(s grpc.ServiceRegistrar, srv SabotageCommandServiceServer) {
	s.RegisterService(&SabotageCommandService_ServiceDesc, srv)
}

// SabotageCommandService_ServiceDesc 서비스 디스크립터
var SabotageCommandService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "jiaa.SabotageCommandService",
	HandlerType: (*SabotageCommandServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExecuteSabotage",
			Handler:    _SabotageCommandService_ExecuteSabotage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}

func _SabotageCommandService_ExecuteSabotage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SabotageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SabotageCommandServiceServer).ExecuteSabotage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/jiaa.SabotageCommandService/ExecuteSabotage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SabotageCommandServiceServer).ExecuteSabotage(ctx, req.(*SabotageRequest))
	}
	return interceptor(ctx, in, info, handler)
}
